services:
  kong:
    image: kong:3.9.0
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kong-business
      - kong-pgadmin
      - kong-grafana
    deploy:
      mode: replicated
      replicas: 1

  business-logic:
    image: earthbert/idp-business-logic
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - kong-business
      - backend
      - logging
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-retries: "5"
        loki-batch-size: "400" 
        loki-timeout: "10s"
        max-size: "10m"
        loki-external-labels: job=business-logic,owner=FakeAcad,environment=development
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  auth:
    image: earthbert/idp-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - logging
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-retries: "5"
        loki-batch-size: "400" 
        loki-timeout: "10s"
        max-size: "10m"
        loki-external-labels: job=auth,owner=FakeAcad,environment=development
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  io-service:
    image: earthbert/idp-io-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - io-database
      - backend
      - logging
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-retries: "5"
        loki-batch-size: "400" 
        loki-timeout: "10s"
        max-size: "10m"
        loki-external-labels: job=io-service,owner=FakeAcad,environment=development
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  backend-app-db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: fakeacad-db
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-vol:/var/lib/postgresql/data
    networks:
      - io-database
      - logging
      - pgadmin-database
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-retries: "5"
        loki-batch-size: "400" 
        loki-timeout: "10s"
        max-size: "10m"
        loki-external-labels: job=backend-app-db,owner=FakeAcad,environment=development
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    networks:
      - kong-pgadmin
      - pgadmin-database
    deploy:
      mode: replicated
      replicas: 1

  agent:
    image: portainer/agent:2.11.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "10000:8000"
    volumes:
      - portainer-vol:/data
    networks:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  loki:
    image: grafana/loki
    volumes:
      - ./loki.yml:/etc/config/loki.yml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yml
    networks:
      - logging
      - visualizing
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-vol:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:8000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - visualizing
      - kong-grafana

volumes:
  kong-db-vol:
    driver: local
  app-db-vol:
    driver: local
  pgadmin-vol:
    driver: local
  portainer-vol:
    driver: local
  grafana-vol:
    driver: local

networks:
  io-database:
    driver: overlay
  backend:
    driver: overlay
  kong-business:
    driver: overlay
  kong-pgadmin:
    driver: overlay
  kong-grafana:
    driver: overlay
  pgadmin-database:
    driver: overlay
  agent:
    driver: overlay
  logging:
    driver: overlay
  visualizing:
    driver: overlay
