name: Build and Push Docker Images

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push AuthService
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/FakeAcad.AuthService/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/idp-auth:latest
      -
        name: Build and push BusinessLogic
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/FakeAcad.BusinessLogic/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/idp-business-logic:latest
      -
        name: Build and push IOManager
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/FakeAcad.IOManager/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/idp-io-service:latest
